token

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,12 +13,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
         with:
@@ -26,17 +20,21 @@ jobs:
 
       - name: Deploy to VM
         run: |
-          ssh -o StrictHostKeyChecking=no apavlov@176.109.110.128 << 'EOF'
-          git clone git@github.com:puffds/dices.git /home/apavlov/dices
-
-#            if [ -f "./gradlew" ]; then
-#              chmod +x gradlew
-#              ./gradlew build
-#            else
-#              echo "gradlew not found!"
-#              exit 1
-#            fi
-          
+          ssh -o StrictHostKeyChecking=no user@your_vm_ip << 'EOF'
+            mkdir -p /home/apavlov/dices
+            cd /home/apavlov/dices
+            if [ ! -d ".git" ]; then
+              git clone https://github.com/puffds/dices.git
+            else
+              git pull origin master
+            fi
+            if [ -f "./gradlew" ]; then
+              chmod +x ./gradlew
+              ./gradlew build
+            else
+              echo "gradlew not found!"
+              exit 1
+            fi
             pkill -f 'java -jar' || true
             nohup java -jar build/libs/dices-1.0.jar &
           EOF
